%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/mjmccalla/Downloads/penglings.csv
%
% Auto-generated by MATLAB on 27-Jan-2026 16:52:21

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "species", "island", "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "sex", "year"];
opts.VariableTypes = ["double", "categorical", "categorical", "double", "double", "double", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["species", "island", "sex"], "EmptyFieldRule", "auto");

% Import the data
penglings_1 = readtable("/home/mjmccalla/Downloads/penglings.csv", opts);


%% Clear temporary variables
clear opts
%%
penglings_Adelie = penglings_1(ismember(penglings_1.species, 'Adelie'), :);
penglings_Gentoo = penglings_1(ismember(penglings_1.species, 'Gentoo'), :);
penglings_Chinstrap = penglings_1(ismember(penglings_1.species, 'Chinstrap'), :);
f = figure("Colormap",[0.9 0.6 0; 0.7 0.1 0.9; 0 0.7 0.7])

hold on
bc1 = bubblechart(penglings_Adelie.flipper_length_mm,penglings_Adelie.body_mass_g,penglings_Adelie.bill_length_mm,[0.9 0.6 0])
bc2 = bubblechart(penglings_Gentoo.flipper_length_mm,penglings_Gentoo.body_mass_g,penglings_Gentoo.bill_length_mm,[0 0.7 0.7])
bc3 = bubblechart(penglings_Chinstrap.flipper_length_mm,penglings_Chinstrap.body_mass_g,penglings_Chinstrap.bill_length_mm,[0.7 0.1 0.9])
hold off
bc1.MarkerFaceAlpha = 0.8;
bc2.MarkerFaceAlpha = 0.8;
bc3.MarkerFaceAlpha = 0.8;

bubblesize([5,20])

xlim([169,235])
ylim([2500,6500])

xlabel("Flipper Length (mm)")
ylabel("Body Mass (g)")
bubblelegend("Bill Length (mm)","NumBubbles",2)
lgd = legend(["Adelie","Gentoo","Chinstrap"])